// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HalPlatformApi.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include "ApiHelper.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class HalPlatformApiHandler : virtual public HalPlatformApiIf {
 public:
  HalPlatformApiHandler() {
    // Your initialization goes here
  }

  void PsuGetModel(std::string& _return, const std::string& name) {
    helper->PsuGetModel(_return, name);
  }

  void PsuGetSerial(std::string& _return, const std::string& name) {
    helper->PsuGetSerial(_return, name);
  }

  void PsuGetRevision(std::string& _return, const std::string& name) {
    helper->PsuGetRevision(_return, name);
  }

  bool PsuGetPresence(const std::string& name) {
    return helper->PsuGetPresence(name);
  }

  bool PsuGetStatus(const std::string& name) {
    return helper->PsuGetStatus(name);
  }

  bool PsuIsReplaceable(const std::string& name) {
    return helper->PsuIsReplaceable(name);
  }

  double PsuGetVoltage(const std::string& name) {
    return helper->PsuGetVoltage(name);
  }

  double PsuGetCurrent(const std::string& name) {
    return helper->PsuGetCurrent(name);
  }

  double PsuGetPower(const std::string& name) {
    return helper->PsuGetPower(name);
  }

  double PsuGetTemp(const std::string& name) {
    return helper->PsuGetTemp(name);
  }

  double PsuGetInputVoltage(const std::string& name) {
    return helper->PsuGetInputVoltage(name);
  }

  double PsuGetInputCurrent(const std::string& name) {
    return helper->PsuGetInputCurrent(name);
  }

  void PsuGetLedState(std::string& _return, const std::string& name) {
    helper->PsuGetLedState(_return, name);
  }

  bool PsuSetLedState(const std::string& name, const std::string& state) {
    return helper->PsuSetLedState(name, state);
  }

  void FanGetModel(std::string& _return, const std::string& name) {
    helper->FanGetModel(_return, name);
  }

  void FanGetSerial(std::string& _return, const std::string& name) {
    helper->FanGetSerial(_return, name);
  }

  void FanGetRevision(std::string& _return, const std::string& name) {
    helper->FanGetRevision(_return, name);
  }

  bool FanGetPresence(const std::string& name) {
    return helper->FanGetPresence(name);
  }

  bool FanGetStatus(const std::string& name) {
    return helper->FanGetStatus(name);
  }

  bool FanIsReplaceable(const std::string& name) {
    return helper->FanIsReplaceable(name);
  }

  void FanGetDirection(std::string& _return, const std::string& name) {
    helper->FanGetDirection(_return, name);
  }

  int32_t FanGetSpeed(const std::string& name) {
    return helper->FanGetSpeed(name);
  }

  int32_t FanGetTargetSpeed(const std::string& name) {
    return helper->FanGetTargetSpeed(name);
  }

  int32_t FanGetSpeedTolerance(const std::string& name) {
    return helper->FanGetSpeedTolerance(name);
  }

  bool FanSetSpeed(const std::string& name, const int32_t speed) {
    return helper->FanSetSpeed(name, speed);
  }

  void FanGetLedState(std::string& _return, const std::string& name) {
    helper->FanGetLedState(_return, name);
  }

  bool FanSetLedState(const std::string& name, const std::string& state) {
    return helper->FanSetLedState(name, state);
  }

  int32_t FanGetPositionInParent(const std::string& name) {
    return helper->FanGetPositionInParent(name);
  }

  bool FanDrawerGetPresence(const std::string& name) {
    return helper->FanDrawerGetPresence(name);
  }

  bool FanDrawerGetStatus(const std::string& name) {
    return helper->FanDrawerGetStatus(name);
  }

  bool FanDrawerIsReplaceable(const std::string& name) {
    return helper->FanDrawerIsReplaceable(name);
  }

  void FanDrawerGetLedState(std::string& _return, const std::string& name) {
    helper->FanDrawerGetLedState(_return, name);
  }

  bool FanDrawerSetLedState(const std::string& name, const std::string& state) {
    return helper->FanDrawerSetLedState(name, state);
  }

  void LedGetState(std::string& _return, const std::string& name) {
    helper->LedGetState(_return, name);
  }

  bool LedSetState(const std::string& name, const std::string& state) {
    return helper->FanDrawerSetLedState(name, state);
  }

  double ThermalGetTemp(const std::string& name) {
    return helper->ThermalGetTemp(name);
  }

  double ThermalGetHighThreshold(const std::string& name) {
    return helper->ThermalGetHighThreshold(name);
  }

  double ThermalGetLowThreshold(const std::string& name) {
    return helper->ThermalGetLowThreshold(name);
  }

  bool ThermalSetHighThreshold(const std::string& name, const double value) {
    return helper->ThermalSetHighThreshold(name, value);
  }

  bool ThermalSetLowThreshold(const std::string& name, const double value) {
    return helper->ThermalSetLowThreshold(name, value);
  }

  double ThermalGetHighCriticalThreshold(const std::string& name) {
    return helper->ThermalGetHighCriticalThreshold(name);
  }

  double ThermalGetLowCriticalThreshold(const std::string& name) {
    return helper->ThermalGetLowCriticalThreshold(name);
  }

  bool ThermalSetHighCriticalThreshold(const std::string& name, const double value) {
    return helper->ThermalSetHighCriticalThreshold(name, value);
  }

  bool ThermalSetLowCriticalThreshold(const std::string& name, const double value) {
    return helper->ThermalSetLowCriticalThreshold(name, value);
  }

  double ThermalGetMinimumRecorded(const std::string& name) {
    return helper->ThermalGetMinimumRecorded(name);
  }

  double ThermalGetMaximumRecorded(const std::string& name) {
    return helper->ThermalGetMaximumRecorded(name);
  }

  bool WatchDogArm(const int32_t index, const int32_t seconds) {
    return helper->WatchDogArm(index, seconds);
  }

  bool WatchDogDisrm(const int32_t index) {
    return helper->WatchDogDisrm(index);
  }

  bool WatchDogIsArmed(const int32_t index) {
    return helper->WatchDogIsArmed(index);
  }

  void ChassisGetName(std::string& _return) {
    helper->ChassisGetName(_return);
  }

  void ChassisGetModel(std::string& _return) {
    helper->ChassisGetModel(_return);
  }

  void ChassisGetSerial(std::string& _return) {
    helper->ChassisGetSerial(_return);
  }

  void ChassisGetRevision(std::string& _return) {
    helper->ChassisGetRevision(_return);
  }

  void ChassisGetBaseMac(std::string& _return) {
    helper->ChassisGetBaseMac(_return);
  }

  int32_t ChassisGetSlot() {
    return helper->ChassisGetSlot();
  }

  void ChassisGetLedState(std::string& _return) {
    helper->ChassisGetLedState(_return);
  }

  bool ChassisSetLedState(const std::string& state) {
    return helper->ChassisSetLedState(state);
  }

  void ChassisGetList(std::string& _return) {
    helper->ChassisGetList(_return);
  }

   bool ChassisIsModular() {
    return helper->ChassisIsModular();
  }

  void ModuleGetModel(std::string& _return, const std::string& name) {
    helper->ModuleGetModel(_return, name);
  }

  void ModuleGetSerial(std::string& _return, const std::string& name) {
    helper->ModuleGetSerial(_return, name);
  }

  void ModuleGetRevision(std::string& _return, const std::string& name) {
    helper->ModuleGetRevision(_return, name);
  }

  void ModuleGetBaseMac(std::string& _return, const std::string& name) {
    helper->ModuleGetBaseMac(_return, name);
  }

  int32_t ModuleGetSlot(const std::string& name) {
    return helper->ModuleGetSlot(name);
  }

  void ModuleGetType(std::string& _return, const std::string& name) {
    helper->ModuleGetType(_return, name);
  }

  void ModuleGetStatus(std::string& _return, const std::string& name) {
    helper->ModuleGetStatus(_return, name);
  }

  double ModuleGetTemp(const std::string& name) {
    return helper->ModuleGetTemp(name);
  }

  void ModuleGetLedState(std::string& _return, const std::string& name) {
    helper->ModuleGetLedState(_return, name);
  }

  bool ModuleSetLedState(const std::string& name, const std::string& state) {
    return helper->ModuleSetLedState(name, state);
  }

  void ComponentGetFwVer(std::string& _return, const std::string& name) {
    helper->ComponentGetFwVer(_return, name);
  }

private:
  ::std::shared_ptr<HalPlatformApiIf> helper = ::std::make_shared<ApiHelper>();

};

int main(int argc, char **argv) {
  ::std::shared_ptr<HalPlatformApiHandler> handler(new HalPlatformApiHandler());
  ::std::shared_ptr<TProcessor> processor(new HalPlatformApiProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(DEF_THRIFT_ADDR, DEF_THRIFT_PORT));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TThreadedServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

