#pragma once

#include "HalApi.h"
#include "HalApiData.h"


class ApiHelper : public HalApiIf
{
public:
    ApiHelper() = default;
    ~ApiHelper() = default;

    /* HalApiIf */
    void BOARD_GetChassisMfg(CMfg_rsp& _return);
    int32_t BOARD_SetChassisMfg(const std::string& pcFilePath);
    int32_t BOARD_SetChassisConfigType(const std::string& pcConfigType);
    void BOARD_GetChassisCali(CCali_rsp& _return);
    int32_t BOARD_SetChassisCali(const std::string& pcFilePath);
    int32_t BOARD_GetChassisCfg(const int32_t uiAddrSlice, const std::string& pcFilePath);
    int32_t BOARD_SetChassisCfg(const int32_t uiAddrSlice, const int32_t uiSize, const std::string& pcFilePath);
    void BOARD_GetUpgInfo(binary_rsp& _return, const int32_t ulLen);
    int32_t BOARD_SetUpgInfo(const std::string& pucBuf, const int32_t ulLen);
    void BOARD_GetBdlHead(binary_rsp& _return, const int32_t ulLen);
    int32_t BOARD_SetBdlHead(const std::string& pucBuf, const int32_t ulLen);
    void BOARD_GetStatusData(CBoardStatusData_rsp& _return);
    void BOARD_GetSccMfg(CMfg_rsp& _return);
    int32_t BOARD_SetSccMfg(const std::string& pcFilePath);
    int32_t BOARD_SetResetType(const int8_t ucResetType);
    void BOARD_GetResetType(i8_rsp& _return, const int32_t iIndex);
    int32_t BOARD_CfgWatchDogTime(const bool bEnable, const int8_t ucTimeout);
    void BOARD_GetApsdStatus(bool_list_rsp& _return, const int32_t iIndex);
    int32_t BOARD_SetLedState(const int32_t uiDevIdx, const int32_t uiState);
    int32_t BOARD_ResetLogic(const int32_t uiDevIdx, const int8_t ucResetType);
    int32_t BOARD_UpgradeLogic(const int32_t uiDevIdx, const std::string& c_pcFilePath);
    int32_t BOARD_GetUpgadeStatus();
    void FAN_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx);
    int32_t FAN_SetMfg(const int32_t uiDevIdx, const std::string& pcFilePath);
    int32_t FAN_SetSpeed(const int32_t uiDevIdx, const int32_t uiDuty);
    int32_t FAN_SetControllerEEP(const int32_t uiDevIdx);
    int32_t FAN_SetLed(const int32_t uiDevIdx, const int32_t uiValue);
    void POWER_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx);
    void BOARD_GetProductName(string_rsp& _return, const int32_t nSize);
    void BOARD_GetConfigType(string_rsp& _return, const int32_t nSize);
    int32_t BOARD_GetProductType();
    int32_t BOARD_SetLogLevel(const int32_t uiLogLevel);
    void BOARD_ConvertDevType(i32_rsp& _return, const std::string& pcName);
    void Cv_GetMuxStatusData(CCvMuxStatusData_rsp& _return, const int32_t enCvLine);
    void Cv_GetClientStatusData(CCvClientStatusData_rsp& _return, const int32_t enCvLine);
    void Cv_GetRef(CCvRef_rsp& _return);
    void DBG_ReadLogicReg(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen);
    int32_t DBG_WriteLogicReg(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal);
    void DBG_ReadLogicRegSlc(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen);
    int32_t DBG_WriteLogicRegSlc(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal);
    int32_t DBG_LoopEnable(const bool bEnable);
    int32_t DBG_LoopInterval(const int32_t uiInterval);
    int32_t DBG_IdleEnable(const bool bEnable);
    int32_t DBG_ApsdEnable(const int32_t iIndex, const bool bEnable);
    void DBG_GetAprStatus(i8_rsp& _return, const int32_t uiIndex);
    void DBG_SpiSendCommand(binary_rsp& _return, const int32_t ulChip, const std::string& pucBufW, const int32_t ulLen);
    void DBG_SpiFlashRead(binary_rsp& _return, const int64_t ulChip, const int64_t ulAddr, const int64_t ulLen);
    int32_t DBG_SpiFlashWrite(const int64_t ulChip, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal);
    void DBG_MdioRead(i16_rsp& _return, const int32_t uiIdx, const int32_t ulPhyAddr, const int32_t ulRegAddr);
    int32_t DBG_MdioWrite(const int32_t uiIdx, const int32_t ulPhyAddr, const int32_t ulRegAddr, const int16_t usData);
    void DBG_NetSwitchRead(i16_rsp& _return, const int32_t ulPhyAddr, const int32_t ulRegAddr);
    int32_t DBG_NetSwitchWrite(const int32_t ulPhyAddr, const int32_t ulRegAddr, const int16_t usData);
    void DBG_SwitchPhyRead(i16_rsp& _return, const int32_t ulPhyAddr, const int32_t ulRegAddr);
    int32_t DBG_SwitchPhyWrite(const int32_t ulPhyAddr, const int32_t ulRegAddr, const int16_t usData);
    void DBG_ReadEeprom(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen);
    int32_t DBG_WriteEeprom(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal);
    void EDFA_GetMfg(CMfg_rsp& _return, const int32_t uiDevType);
    void EDFA_GetStatusData(COaStatusData_rsp& _return, const int32_t uiDevType);
    void EDFA_GetCfgData(COaCfgData_rsp& _return, const int32_t uiDevType);
    int32_t EDFA_GetDebugInfo(const int32_t uiDevType, const std::string& pcFilePath);
    int32_t EDFA_GetMcuDebugInfo(const int32_t uiDevType, const std::string& pcFilePath);
    int32_t EDFA_SetGainRange(const int32_t uiDevType, const int16_t sGainRange);
    int32_t EDFA_SetGain(const int32_t uiDevType, const int16_t sGain);
    int32_t EDFA_SetTilt(const int32_t uiDevType, const int16_t sTilt);
    int32_t EDFA_SetMode(const int32_t uiDevType, const int8_t ucMode, const int16_t sVal);
    int32_t EDFA_SetPumpEnable(const int32_t uiDevType, const bool bEnable);
    int32_t EDFA_SetAprEnable(const int32_t uiDevType, const bool bEnable);
    int32_t EDFA_SetAutolosEnable(const int32_t uiDevType, const bool bEnable);
    int32_t EDFA_SetRxLosThr(const int32_t uiDevType, const int16_t sThr, const int16_t sHys);
    int32_t EDFA_SetAttn(const int32_t uiDevType, const int16_t sAttn);
    void EDFA_GetAttn(i16_rsp& _return, const int32_t uiDevType);
    int32_t EDFA_Reset(const int32_t uiDevType, const int8_t ucResetType);
    int32_t EDFA_Upgrade(const int32_t uiDevType, const std::string& c_pcFilePath);
    int32_t EDFA_Swap(const int32_t uiDevType);
    int32_t EDFA_Commit(const int32_t uiDevType);
    int32_t EDFA_GetUpgadeStatus(const int32_t uiDevType);
    void EDFA_DbgRead(binary_rsp& _return, const int32_t uiDevType, const int32_t uiLen);
    int32_t EDFA_DbgWrite(const int32_t uiDevType, const std::string& pucBuf, const int32_t uiLen);
    int32_t EDFA_SetDfbEnable(const int32_t uiDevType, const bool bEnable, const int32_t iPower);
    int32_t EDFA_SetOscEnable(const int32_t uiDevType, const bool bEnable);
    int32_t EDFA_SetOtdrSwitchPos(const int32_t uiDevType, const int32_t uiPos);
    int32_t EDFA_SetOscAddThrHys(const int32_t uiDevType, const int16_t sThr, const int16_t sHys);
    int32_t EDFA_SetOscDropThrHys(const int32_t uiDevType, const int16_t sThr, const int16_t sHys);
    int32_t EDFA_SetOscRxThrHys(const int32_t uiDevType, const int16_t sThr, const int16_t sHys);
    int32_t EDFA_SetApsdEnable(const int32_t uiDevType, const bool bEnable);
    void EDFA_GetApsdStatus(bool_list_rsp& _return, const int32_t uiDevType);
    void EDFA_GetOcmAttn(i16_rsp& _return, const int32_t uiDevType);
    int32_t EDFA_SetUpgState(const int32_t uiDevType, const int16_t sState);
    int32_t EDFA_SetLedState(const int32_t uiDevType, const int16_t sState);
    int32_t EDFA_SetLedAlm(const int32_t uiDevType, const int16_t sState);
    void EDFA_GetCali(COaCaliData_rsp& _return, const int32_t uiDevType);
    int32_t EDFA_SetOtdrCali(const int32_t uiDevType, const std::string& pcFilePath);
    int32_t EDFA_SetOcmCali(const int32_t uiDevType, const std::string& pcFilePath);
    int32_t EDFA_SetManualVoaEnable(const int32_t uiDevType, const bool bEnable);
    int32_t EDFA_SetPaddingVoaConfigPower(const int32_t uiDevType, const int16_t sOutPower);
    int32_t EDFA_SetManualGainEnable(const int32_t uiDevType, const bool bEnable);
    int32_t EDFA_SetThr(const int32_t uiDevType, const int32_t uiPortIdx, const int32_t uiType, const int16_t sThr, const int16_t sHys);
    int32_t EDFA_SetPumpCurrent(const int32_t uiDevType, const int32_t uiPumpIdx, const int16_t sCurrent);
    int32_t EDFA_SetAlmMask(const int32_t uiDevType, const int32_t iMaskIdx, const int32_t iMaskVal);
    void EDFA_GetEventLog(COaEventLogAllData_rsp& _return, const int32_t uiDevType);
    int32_t EDFA_SetShutterState(const int32_t uiDevType, const bool block);
    void EDFA_GetShutterState(bool_rsp& _return, const int32_t uiDevType);
    void EXTEND_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx);
    void EXTEND_GetStatusData(CExtendStatusData_rsp& _return, const int32_t uiDevIdx);
    int32_t EXTEND_Reset(const int32_t uiDevIdx, const int8_t ucResetType);
    int32_t EXTEND_Upgrade(const int32_t uiDevIdx, const std::string& c_pcFilePath);
    int32_t EXTEND_GetUpgadeStatus(const int32_t uiDevIdx);
    void EXTEND_DbgRead(binary_rsp& _return, const int32_t uiDevIdx, const int32_t uiLen);
    int32_t EXTEND_DbgWrite(const int32_t uiDevIdx, const std::string& pucBuf, const int32_t uiLen);
    int32_t EXTEND_SetSfp(const int32_t uiDevIdx, const int32_t ulVal);
    void MIRROR_GetStatusData(CMirrorData_rsp& _return, const int32_t uiDevIdx);
    int32_t SWITCH_Pos(const int32_t uiDevIdx, const int32_t uiPort);
    void MUX_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx);
    void MUX_GetStatusData(CMuxStatusData_rsp& _return, const int32_t uiDevIdx);
    void MUX_GetCali(CMuxCaliData_rsp& _return, const int32_t uiDevIdx);
    void OCM_GetMfg(CMfg_rsp& _return, const int32_t uiDevType);
    void OCM_GetStatusData(COcmStatusData_rsp& _return, const int32_t uiDevType);
    void OCM_GetChPower(COcmChPower_rsp& _return, const int32_t uiDevType, const int32_t uiPortId);
    void OCM_GetOsaData(COcmOsa_rsp& _return, const int32_t uiDevType, const int32_t uiPortId);
    void OCM_GetRealTimeOsaData(COcmOsa_rsp& _return, const int32_t uiDevType, const int32_t uiPortId);
    int32_t OCM_SetWaveplan(const int32_t uiDevType, const int32_t uiPortId, const int32_t uiChCnt, const std::vector<CWavePlanSlice_t> & pstWavePlan);
    int32_t OCM_SetOcmWaveplan(const int32_t uiDevType, const int32_t uiPortId, const int32_t uiChCnt, const std::vector<STChannelGrid_t> & pstWavePlan);
    int32_t OCM_Reset(const int32_t uiDevType, const int8_t ucResetType);
    int32_t OCM_Upgrade(const int32_t uiDevType, const std::string& c_pcFilePath);
    int32_t OCM_Commit(const int32_t uiDevType);
    int32_t OCM_GetUpgradeStatus(const int32_t uiDevType);
    int32_t OCM_SetVoa(const int32_t uiDevType, const int16_t sAttn);
    void OCM_GetVoa(i16_rsp& _return, const int32_t uiDevType);
    void OCM_GetVoaPd(i16_list_rsp& _return, const int32_t uiDevType);
    void OCS_GetMfg(CMfg_rsp& _return, const int32_t uiDevType);
    void OCS_GetStatusData(COcsStatusData_rsp& _return, const int32_t uiDevType);
    int32_t OCS_SetConnection(const int32_t uiDevType, const COcsConnection_t& pstConnection);
    int32_t OCS_SetConnections(const int32_t uiDevType, const COcsConnections_t& pstConnections);
    int32_t OCS_SetLedState(const int32_t uiDevType, const int32_t index, const int32_t uiState);
    int32_t OCS_SetLedMode(const int32_t uiDevType, const int32_t uiMode);
    int32_t OCS_Reset(const int32_t uiDevType, const int8_t ucResetType);
    int32_t OCS_Upgrade(const int32_t uiDevType, const std::string& pcPath);
    int32_t OCS_GetUpgradeStatus(const int32_t uiDevType);
    void OPS_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx);
    void OPS_GetCommStatusData(COpsCommStatusData_rsp& _return, const int32_t uiDevIdx);
    void OPS_GetCfgData(COpsCfgData_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId);
    void OPS_GetStatusData(COpsStatusData_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId);
    void OPS_GetHistoryData(COpsHistoryData_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId);
    void OPS_GetLedStatus(COpsLed_rsp& _return, const int32_t uiDevIdx);
    int32_t OPS_ClearAlarmDuration(const int32_t uiDevIdx);
    int32_t OPS_SetThrPwrDiff(const int32_t uiDevIdx, const int16_t sThr, const int16_t sHys, const int32_t uiPortId);
    int32_t OPS_SetThrLine(const int32_t uiDevIdx, const int32_t uiPortIdx, const int16_t sThr, const int16_t sHys, const int32_t uiPortId);
    int32_t OPS_SetPortPowerThr(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sThr, const int32_t uiPortId);
    int32_t OPS_SetPortPowerHys(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sHys, const int32_t uiPortId);
    int32_t OPS_SetWtr(const int32_t uiDevIdx, const int32_t uiWtr, const int32_t uiPortId);
    int32_t OPS_SetHoldOffTime(const int32_t uiDevIdx, const int32_t uiHoldOffTime, const int32_t uiPortId);
    int32_t OPS_SetRevertive(const int32_t uiDevIdx, const bool bRevertive, const int32_t uiPortId);
    int32_t OPS_SetMode(const int32_t uiDevIdx, const int32_t uiMode, const int32_t uiPortId);
    int32_t OPS_SetRelativeThr(const int32_t uiDevIdx, const int16_t sThr, const int32_t uiPortId);
    int32_t OPS_SetRelativeOffset(const int32_t uiDevIdx, const int16_t sOffset, const int32_t uiPortId);
    int32_t OPS_SetSwitchThr(const int32_t uiDevIdx, const int32_t uiPos, const int32_t iThr, const int32_t uiPortId);
    int32_t OPS_SetSwitchHys(const int32_t uiDevIdx, const int32_t uiPos, const int32_t iHys, const int32_t uiPortId);
    int32_t OPS_Reset(const int32_t uiDevIdx, const int8_t ucResetType);
    int32_t OPS_Upgrade(const int32_t uiDevIdx, const std::string& c_pcFilePath);
    int32_t OPS_GetUpgadeStatus(const int32_t uiDevIdx);
    int32_t OPS_SetLedDebugMode(const int32_t uiDevIdx, const int32_t uiMode);
    int32_t OPS_SetLedStatus(const int32_t uiDevIdx, const int32_t uiLedIdx, const int32_t uiStatus);
    int32_t OPS_SetConnectionPdThr(const int32_t uiDevIdx, const int32_t uiPdIdx, const int32_t uiType, const int16_t sThr, const int32_t uiPortId);
    int32_t OPS_SetConnectionPdHys(const int32_t uiDevIdx, const int32_t uiPdIdx, const int32_t uiType, const int16_t sHys, const int32_t uiPortId);
    int32_t OPS_SetAlmMask(const int32_t uiDevType, const int32_t iMaskIdx, const int32_t iMaskVal, const int32_t uiPortId);
    void OPS_GetEventLog(COpsEventLogAllData_rsp& _return, const int32_t uiDevType, const int32_t uiPortId);
    int32_t OPS_SetRemoteStatus(const int32_t uiDevIdx, const COpsReqStatus_t& pstStatus, const int32_t uiPortId);
    void OPS_GetRequestStatus(COpsBidirectionStatus_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId);
    int32_t OPS_SetSwitchingType(const int32_t uiDevIdx, const int8_t ucType, const int32_t uiPortId);
    void OPS_GetOpsDevIdByKey(i32_list_rsp& _return, const std::string& pcName);
    void OSC_GetStatusData(COscStatusData_rsp& _return, const int32_t uiDevType);
    void OSC_GetCfgData(COscCfgData_rsp& _return, const int32_t uiDevType);
    int32_t OSC_SetEnable(const int32_t uiDevType, const bool bEnable);
    int32_t OSC_SetVoa(const int32_t uiDevType, const int32_t uiTxRx, const int16_t sAttn);
    void OSC_GetVoa(i16_rsp& _return, const int32_t uiDevType, const int32_t uiTxRx);
    int32_t OSC_SetSwitchPos(const int32_t uiDevType, const COscSwitchPosSet_t& rstSwitchPos);
    void OSC_GetSwitchPos(COscSwitchPos_rsp& _return, const int32_t uiDevType);
    void OTDR_GetMfg(CMfg_rsp& _return, const int32_t ulDevIdx);
    void OTDR_GetStatusData(COtdrStatusData_rsp& _return, const int32_t ulDevIdx);
    void OTDR_GetCfgData(COtdrCfgData_rsp& _return, const int32_t ulDevIdx);
    int32_t OTDR_StartScan(const int32_t ulDevIdx);
    int32_t OTDR_SetPara(const int32_t ulDevIdx, const int32_t ulDistRang, const int32_t ulPulseWidth, const double dSamplingResolution);
    int32_t OTDR_SetMeasuringTime(const int32_t ulDevIdx, const int32_t ulMeasuringTime);
    int32_t OTDR_SetUserIOR(const int32_t ulDevIdx, const double dUserIOR);
    int32_t OTDR_SetThr(const int32_t ulDevIdx, const double dRefThr, const double dSpliceLosThr, const double dFiberEndThr);
    int32_t OTDR_Reset(const int32_t ulDevIdx, const int8_t ucResetType);
    int32_t OTDR_Upgrade(const int32_t ulDevIdx, const std::string& c_pcFilePath);
    int32_t OTDR_GetUpgadeStatus(const int32_t ulDevIdx);
    void OTDR_DbgRead(binary_rsp& _return, const int32_t ulDevIdx, const int32_t uiLen);
    int32_t OTDR_DbgWrite(const int32_t ulDevIdx, const std::string& pucBuf, const int32_t uiLen);
    int32_t OTDR_SetScanMode(const int32_t uiDevType, const int32_t ulScanMode);
    int32_t OTDR_SetStartOffset(const int32_t uiDevType, const COtdrStartOffset_t& pstStartOffset);
    void OTDR_GetStartOffset(COtdrStartOffset_rsp& _return, const int32_t uiDevType);
    int32_t OTDR_StartScanPort(const int32_t ulDevIdx, const int32_t ulPortId);
    void SLOT_GetDevIdx(i32_list_rsp& _return, const int32_t uiDevType);
    int32_t SLOT_SetOnline(const int32_t uiSlotIdx, const bool bOnline);
    void SLOT_GetSlotNum(i32_rsp& _return);
    int32_t SLOT_SetMfg(const int32_t uiSlotIdx, const std::string& c_pcFilePath);
    void SLOT_GetMfg(CMfg_rsp& _return, const int32_t uiSlotIdx);
    void SLOT_GetStatusData(CSlotStatusData_rsp& _return, const int32_t uiSlotIdx);
    int32_t SLOT_ClearPlugFlag(const int32_t uiSlotIdx);
    void SLOT_GetInfo(CSlotInfo_rsp& _return, const int32_t uiSlotIdx);
    void SLOT_GetCali(CCali_rsp& _return, const int32_t uiSlotIdx);
    int32_t SLOT_SetCali(const int32_t uiSlotIdx, const std::string& c_pcFilePath);
    int32_t SLOT_Reset(const int32_t uiSlotIdx, const int8_t ucResetType);
    int32_t SLOT_SetLed(const int32_t uiSlotIdx, const int32_t uiLedIdx, const int32_t uiState);
    void SLOT_ReadEeprom(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen);
    int32_t SLOT_WriteEeprom(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal);
    void TDCM_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx);
    void TDCM_GetStatusData(CTdcmStatusData_rsp& _return, const int32_t uiDevIdx);
    void TDCM_GetCfgData(CTdcmCfgData_rsp& _return, const int32_t uiDevIdx);
    int32_t TDCM_SetFrequency(const int32_t uiDevIdx, const double fFrequency);
    int32_t TDCM_SetDispersion(const int32_t uiDevIdx, const double fDispersion);
    int32_t TDCM_Reset(const int32_t uiDevIdx, const int8_t ucResetType);
    void WSS_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx);
    void WSS_GetCfg(CWssAllCfg_rsp& _return, const int32_t uiDevIdx);
    void WSS_GetOscCfg(CWssAllCfg_rsp& _return, const int32_t uiDevIdx);
    void WSS_GetStatusData(CWssStatusData_rsp& _return, const int32_t uiDevIdx);
    int32_t WSS_SetAllChCfg(const int32_t uiDevIdx, const int32_t uiSubIdx, const int32_t uiChCnt, const std::vector<CWssCfg_t> & pstWssCfg);
    int32_t WSS_SetOscChCfg(const int32_t uiDevIdx, const int32_t uiSubIdx, const int32_t uiChCnt, const std::vector<CWssCfg_t> & pstWssCfg);
    int32_t WSS_SetWaveplan(const int32_t uiDevIdx, const int32_t uiSubIdx, const int32_t uiChCnt, const std::vector<CWavePlan_t> & pstWavePlan);
    int32_t WSS_SetPortPowerThr(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sThr);
    int32_t WSS_SetPortPowerHys(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sHys);
    int32_t WSS_GetPortPowerHistory(const int32_t uiDevIdx);
    int32_t WSS_SetLedMode(const int32_t uiDevIdx, const int32_t uiMode);
    int32_t WSS_SetLedDebugMode(const int32_t uiDevIdx, const int32_t uiMode);
    int32_t WSS_SetLedStatus(const int32_t uiDevIdx, const int32_t uiLedIdx, const int32_t uiStatus);
    int32_t WSS_Reset(const int32_t uiDevIdx, const int8_t ucResetType);
    int32_t WSS_Upgrade(const int32_t uiDevIdx, const std::string& c_pcFilePath);
    int32_t WSS_GetUpgradeStatus(const int32_t uiDevIdx);
    int32_t WSS_SetUserData(const int32_t uiDevIdx, const std::string& pucData, const int32_t nLen);
    void WSS_GetUserData(binary_rsp& _return, const int32_t uiDevIdx, const int32_t nLen);
    int32_t WSS_SetPmUserData(const int32_t uiDevIdx, const std::string& pucData, const int32_t nLen);
    void WSS_GetPmUserData(binary_rsp& _return, const int32_t uiDevIdx, const int32_t nLen);

};