// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HalApi.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include "ApiHelper.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class HalApiHandler : virtual public HalApiIf {
 public:
  HalApiHandler() {
    // Your initialization goes here
  }

  void BOARD_GetChassisMfg(CMfg_rsp& _return) {
    helper->BOARD_GetChassisMfg(_return);
  }

  int32_t BOARD_SetChassisMfg(const std::string& pcFilePath) {
    return helper->BOARD_SetChassisMfg(pcFilePath);
  }

  int32_t BOARD_SetChassisConfigType(const std::string& pcConfigType) {
    return helper->BOARD_SetChassisConfigType(pcConfigType);
  }

  void BOARD_GetChassisCali(CCali_rsp& _return) {
    helper->BOARD_GetChassisCali(_return);
  }

  int32_t BOARD_SetChassisCali(const std::string& pcFilePath) {
    return helper->BOARD_SetChassisCali(pcFilePath);
  }

  int32_t BOARD_GetChassisCfg(const int32_t uiAddrSlice, const std::string& pcFilePath) {
    return helper->BOARD_GetChassisCfg(uiAddrSlice, pcFilePath);
  }

  int32_t BOARD_SetChassisCfg(const int32_t uiAddrSlice, const int32_t uiSize, const std::string& pcFilePath) {
    return helper->BOARD_SetChassisCfg(uiAddrSlice, uiSize, pcFilePath);
  }

  void BOARD_GetUpgInfo(binary_rsp& _return, const int32_t ulLen) {
    helper->BOARD_GetUpgInfo(_return, ulLen);
  }

  int32_t BOARD_SetUpgInfo(const std::string& pucBuf, const int32_t ulLen) {
    return helper->BOARD_SetUpgInfo(pucBuf, ulLen);
  }

  void BOARD_GetBdlHead(binary_rsp& _return, const int32_t ulLen) {
    helper->BOARD_GetBdlHead(_return, ulLen);
  }

  int32_t BOARD_SetBdlHead(const std::string& pucBuf, const int32_t ulLen) {
    return helper->BOARD_SetBdlHead(pucBuf, ulLen);
  }

  void BOARD_GetStatusData(CBoardStatusData_rsp& _return) {
    helper->BOARD_GetStatusData(_return);
  }

  void BOARD_GetSccMfg(CMfg_rsp& _return) {
    helper->BOARD_GetSccMfg(_return);
  }

  int32_t BOARD_SetSccMfg(const std::string& pcFilePath) {
    return helper->BOARD_SetSccMfg(pcFilePath);
  }

  int32_t BOARD_SetResetType(const int8_t ucResetType) {
    return helper->BOARD_SetResetType(ucResetType);
  }

  void BOARD_GetResetType(i8_rsp& _return, const int32_t iIndex) {
    helper->BOARD_GetResetType(_return, iIndex);
  }

  int32_t BOARD_CfgWatchDogTime(const bool bEnable, const int8_t ucTimeout) {
    return helper->BOARD_CfgWatchDogTime(bEnable, ucTimeout);
  }

  void BOARD_GetApsdStatus(bool_list_rsp& _return, const int32_t iIndex) {
    helper->BOARD_GetApsdStatus(_return, iIndex);
  }

  int32_t BOARD_SetLedState(const int32_t uiDevIdx, const int32_t uiState) {
    return helper->BOARD_SetLedState(uiDevIdx, uiState);
  }

  int32_t BOARD_ResetLogic(const int32_t uiDevIdx, const int8_t ucResetType) {
    return helper->BOARD_ResetLogic(uiDevIdx, ucResetType);
  }

  int32_t BOARD_UpgradeLogic(const int32_t uiDevIdx, const std::string& c_pcFilePath) {
    return helper->BOARD_UpgradeLogic(uiDevIdx, c_pcFilePath);
  }

  int32_t BOARD_GetUpgadeStatus() {
    return helper->BOARD_GetUpgadeStatus();
  }

  void FAN_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx) {
    helper->FAN_GetMfg(_return, uiDevIdx);
  }

  int32_t FAN_SetMfg(const int32_t uiDevIdx, const std::string& pcFilePath) {
    return helper->FAN_SetMfg(uiDevIdx, pcFilePath);
  }

  int32_t FAN_SetSpeed(const int32_t uiDevIdx, const int32_t uiDuty) {
    return helper->FAN_SetSpeed(uiDevIdx, uiDuty);
  }

  int32_t FAN_SetControllerEEP(const int32_t uiDevIdx) {
    return helper->FAN_SetControllerEEP(uiDevIdx);
  }

  int32_t FAN_SetLed(const int32_t uiDevIdx, const int32_t uiValue) {
    return helper->FAN_SetLed(uiDevIdx, uiValue);
  }

  void POWER_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx) {
    helper->POWER_GetMfg(_return, uiDevIdx);
  }

  void BOARD_GetProductName(string_rsp& _return, const int32_t nSize) {
    helper->BOARD_GetProductName(_return, nSize);
  }

  void BOARD_GetConfigType(string_rsp& _return, const int32_t nSize) {
    helper->BOARD_GetConfigType(_return, nSize);
  }

  int32_t BOARD_GetProductType() {
    return helper->BOARD_GetProductType();
  }

  int32_t BOARD_SetLogLevel(const int32_t uiLogLevel) {
    return helper->BOARD_SetLogLevel(uiLogLevel);
  }

  void BOARD_ConvertDevType(i32_rsp& _return, const std::string& pcName) {
    helper->BOARD_ConvertDevType(_return, pcName);
  }

  void Cv_GetMuxStatusData(CCvMuxStatusData_rsp& _return, const int32_t enCvLine) {
    helper->Cv_GetMuxStatusData(_return, enCvLine);
  }

  void Cv_GetClientStatusData(CCvClientStatusData_rsp& _return, const int32_t enCvLine) {
    helper->Cv_GetClientStatusData(_return, enCvLine);
  }

  void Cv_GetRef(CCvRef_rsp& _return) {
    helper->Cv_GetRef(_return);
  }

  void DBG_ReadLogicReg(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen) {
    helper->DBG_ReadLogicReg(_return, uiIdx, ulAddr, ulLen);
  }

  int32_t DBG_WriteLogicReg(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal) {
    return helper->DBG_WriteLogicReg(uiIdx, ulAddr, ulLen, pucVal);
  }

  void DBG_ReadLogicRegSlc(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen) {
    helper->DBG_ReadLogicRegSlc(_return, uiIdx, ulAddr, ulLen);
  }

  int32_t DBG_WriteLogicRegSlc(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal) {
    return helper->DBG_WriteLogicRegSlc(uiIdx, ulAddr, ulLen, pucVal);
  }

  int32_t DBG_LoopEnable(const bool bEnable) {
    return helper->DBG_LoopEnable(bEnable);
  }

  int32_t DBG_LoopInterval(const int32_t uiInterval) {
    return helper->DBG_LoopInterval(uiInterval);
  }

  int32_t DBG_IdleEnable(const bool bEnable) {
    return helper->DBG_IdleEnable(bEnable);
  }

  int32_t DBG_ApsdEnable(const int32_t iIndex, const bool bEnable) {
    return helper->DBG_ApsdEnable(iIndex, bEnable);
  }

  void DBG_GetAprStatus(i8_rsp& _return, const int32_t uiIndex) {
    helper->DBG_GetAprStatus(_return, uiIndex);
  }

  void DBG_SpiSendCommand(binary_rsp& _return, const int32_t ulChip, const std::string& pucBufW, const int32_t ulLen) {
    return helper->DBG_SpiSendCommand(_return, ulChip, pucBufW, ulLen);
  }

  void DBG_SpiFlashRead(binary_rsp& _return, const int64_t ulChip, const int64_t ulAddr, const int64_t ulLen) {
    helper->DBG_SpiFlashRead(_return, ulChip, ulAddr, ulLen);
  }

  int32_t DBG_SpiFlashWrite(const int64_t ulChip, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal) {
    return helper->DBG_SpiFlashWrite(ulChip, ulAddr, ulLen, pucVal);
  }

  void DBG_MdioRead(i16_rsp& _return, const int32_t uiIdx, const int32_t ulPhyAddr, const int32_t ulRegAddr) {
    helper->DBG_MdioRead(_return, uiIdx, ulPhyAddr, ulRegAddr);
  }

  int32_t DBG_MdioWrite(const int32_t uiIdx, const int32_t ulPhyAddr, const int32_t ulRegAddr, const int16_t usData) {
    return helper->DBG_MdioWrite(uiIdx, ulPhyAddr, ulRegAddr, usData);
  }

  void DBG_NetSwitchRead(i16_rsp& _return, const int32_t ulPhyAddr, const int32_t ulRegAddr) {
    helper->DBG_NetSwitchRead(_return, ulPhyAddr, ulRegAddr);
  }

  int32_t DBG_NetSwitchWrite(const int32_t ulPhyAddr, const int32_t ulRegAddr, const int16_t usData) {
    return helper->DBG_NetSwitchWrite(ulPhyAddr, ulRegAddr, usData);
  }

  void DBG_SwitchPhyRead(i16_rsp& _return, const int32_t ulPhyAddr, const int32_t ulRegAddr) {
    helper->DBG_SwitchPhyRead(_return, ulPhyAddr, ulRegAddr);
  }

  int32_t DBG_SwitchPhyWrite(const int32_t ulPhyAddr, const int32_t ulRegAddr, const int16_t usData) {
    return helper->DBG_SwitchPhyWrite(ulPhyAddr, ulRegAddr, usData);
  }

  void DBG_ReadEeprom(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen) {
    helper->DBG_ReadEeprom(_return, uiIdx, ulAddr, ulLen);
  }

  int32_t DBG_WriteEeprom(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal) {
    return helper->DBG_WriteEeprom(uiIdx, ulAddr, ulLen, pucVal);
  }

  void EDFA_GetMfg(CMfg_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetMfg(_return, uiDevType);
  }

  void EDFA_GetStatusData(COaStatusData_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetStatusData(_return, uiDevType);
  }

  void EDFA_GetCfgData(COaCfgData_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetCfgData(_return, uiDevType);
  }

  int32_t EDFA_GetDebugInfo(const int32_t uiDevType, const std::string& pcFilePath) {
    return helper->EDFA_GetDebugInfo(uiDevType, pcFilePath);
  }

  int32_t EDFA_GetMcuDebugInfo(const int32_t uiDevType, const std::string& pcFilePath) {
    return helper->EDFA_GetMcuDebugInfo(uiDevType, pcFilePath);
  }

  int32_t EDFA_SetGainRange(const int32_t uiDevType, const int16_t sGainRange) {
    return helper->EDFA_SetGainRange(uiDevType, sGainRange);
  }

  int32_t EDFA_SetGain(const int32_t uiDevType, const int16_t sGain) {
    return helper->EDFA_SetGain(uiDevType, sGain);
  }

  int32_t EDFA_SetTilt(const int32_t uiDevType, const int16_t sTilt) {
    return helper->EDFA_SetTilt(uiDevType, sTilt);
  }

  int32_t EDFA_SetMode(const int32_t uiDevType, const int8_t ucMode, const int16_t sVal) {
    return helper->EDFA_SetMode(uiDevType, ucMode, sVal);
  }

  int32_t EDFA_SetPumpEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->EDFA_SetPumpEnable(uiDevType, bEnable);
  }

  int32_t EDFA_SetAprEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->EDFA_SetAprEnable(uiDevType, bEnable);
  }

  int32_t EDFA_SetAutolosEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->EDFA_SetAutolosEnable(uiDevType, bEnable);
  }

  int32_t EDFA_SetRxLosThr(const int32_t uiDevType, const int16_t sThr, const int16_t sHys) {
    return helper->EDFA_SetRxLosThr(uiDevType, sThr, sHys);
  }

  int32_t EDFA_SetAttn(const int32_t uiDevType, const int16_t sAttn) {
    return helper->EDFA_SetAttn(uiDevType, sAttn);
  }

  void EDFA_GetAttn(i16_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetAttn(_return, uiDevType);
  }

  int32_t EDFA_Reset(const int32_t uiDevType, const int8_t ucResetType) {
    return helper->EDFA_Reset(uiDevType, ucResetType);
  }

  int32_t EDFA_Upgrade(const int32_t uiDevType, const std::string& c_pcFilePath) {
    return helper->EDFA_Upgrade(uiDevType, c_pcFilePath);
  }

  int32_t EDFA_Swap(const int32_t uiDevType) {
    return helper->EDFA_Swap(uiDevType);
  }

  int32_t EDFA_Commit(const int32_t uiDevType) {
    return helper->EDFA_Commit(uiDevType);
  }

  int32_t EDFA_GetUpgadeStatus(const int32_t uiDevType) {
    return helper->EDFA_GetUpgadeStatus(uiDevType);
  }

  void EDFA_DbgRead(binary_rsp& _return, const int32_t uiDevType, const int32_t uiLen) {
    helper->EDFA_DbgRead(_return, uiDevType, uiLen);
  }

  int32_t EDFA_DbgWrite(const int32_t uiDevType, const std::string& pucBuf, const int32_t uiLen) {
    return helper->EDFA_DbgWrite(uiDevType, pucBuf, uiLen);
  }

  int32_t EDFA_SetDfbEnable(const int32_t uiDevType, const bool bEnable, const int32_t iPower) {
    return helper->EDFA_SetDfbEnable(uiDevType, bEnable, iPower);
  }

  int32_t EDFA_SetOscEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->EDFA_SetOscEnable(uiDevType, bEnable);
  }

  int32_t EDFA_SetOtdrSwitchPos(const int32_t uiDevType, const int32_t uiPos) {
    return helper->EDFA_SetOtdrSwitchPos(uiDevType, uiPos);
  }

  int32_t EDFA_SetOscAddThrHys(const int32_t uiDevType, const int16_t sThr, const int16_t sHys) {
    return helper->EDFA_SetOscAddThrHys(uiDevType, sThr, sHys);
  }

  int32_t EDFA_SetOscDropThrHys(const int32_t uiDevType, const int16_t sThr, const int16_t sHys) {
    return helper->EDFA_SetOscDropThrHys(uiDevType, sThr, sHys);
  }

  int32_t EDFA_SetOscRxThrHys(const int32_t uiDevType, const int16_t sThr, const int16_t sHys) {
    return helper->EDFA_SetOscRxThrHys(uiDevType, sThr, sHys);
  }

  int32_t EDFA_SetApsdEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->EDFA_SetApsdEnable(uiDevType, bEnable);
  }

  void EDFA_GetApsdStatus(bool_list_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetApsdStatus(_return, uiDevType);
  }

  void EDFA_GetOcmAttn(i16_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetOcmAttn(_return, uiDevType);
  }

  int32_t EDFA_SetUpgState(const int32_t uiDevType, const int16_t sState) {
    return helper->EDFA_SetUpgState(uiDevType, sState);
  }

  int32_t EDFA_SetLedState(const int32_t uiDevType, const int16_t sState) {
    return helper->EDFA_SetLedState(uiDevType, sState);
  }

  int32_t EDFA_SetLedAlm(const int32_t uiDevType, const int16_t sState) {
    return helper->EDFA_SetLedAlm(uiDevType, sState);
  }

  void EDFA_GetCali(COaCaliData_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetCali(_return, uiDevType);
  }

  int32_t EDFA_SetOtdrCali(const int32_t uiDevType, const std::string& pcFilePath) {
    return helper->EDFA_SetOtdrCali(uiDevType, pcFilePath);
  }

  int32_t EDFA_SetOcmCali(const int32_t uiDevType, const std::string& pcFilePath) {
    return helper->EDFA_SetOcmCali(uiDevType, pcFilePath);
  }

  int32_t EDFA_SetManualVoaEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->EDFA_SetManualVoaEnable(uiDevType, bEnable);
  }

  int32_t EDFA_SetPaddingVoaConfigPower(const int32_t uiDevType, const int16_t sOutPower) {
    return helper->EDFA_SetPaddingVoaConfigPower(uiDevType, sOutPower);
  }

  int32_t EDFA_SetManualGainEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->EDFA_SetManualGainEnable(uiDevType, bEnable);
  }

  int32_t EDFA_SetThr(const int32_t uiDevType, const int32_t uiPortIdx, const int32_t uiType, const int16_t sThr, const int16_t sHys) {
    return helper->EDFA_SetThr(uiDevType, uiPortIdx, uiType, sThr, sHys);
  }

  int32_t EDFA_SetPumpCurrent(const int32_t uiDevType, const int32_t uiPumpIdx, const int16_t sCurrent) {
    return helper->EDFA_SetPumpCurrent(uiDevType, uiPumpIdx, sCurrent);
  }

  int32_t EDFA_SetAlmMask(const int32_t uiDevType, const int32_t iMaskIdx, const int32_t iMaskVal) {
    return helper->EDFA_SetAlmMask(uiDevType, iMaskIdx, iMaskVal);
  }

  void EDFA_GetEventLog(COaEventLogAllData_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetEventLog(_return, uiDevType);
  }

  int32_t EDFA_SetShutterState(const int32_t uiDevType, const bool block) {
    return helper->EDFA_SetShutterState(uiDevType, block);
  }

  void EDFA_GetShutterState(bool_rsp& _return, const int32_t uiDevType) {
    helper->EDFA_GetShutterState(_return, uiDevType);
  }

  void EXTEND_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx) {
    helper->EXTEND_GetMfg(_return, uiDevIdx);
  }

  void EXTEND_GetStatusData(CExtendStatusData_rsp& _return, const int32_t uiDevIdx) {
    helper->EXTEND_GetStatusData(_return, uiDevIdx);
  }

  int32_t EXTEND_Reset(const int32_t uiDevIdx, const int8_t ucResetType) {
    return helper->EXTEND_Reset(uiDevIdx, ucResetType);
  }

  int32_t EXTEND_Upgrade(const int32_t uiDevIdx, const std::string& c_pcFilePath) {
    return helper->EXTEND_Upgrade(uiDevIdx, c_pcFilePath);
  }

  int32_t EXTEND_GetUpgadeStatus(const int32_t uiDevIdx) {
    return helper->EXTEND_GetUpgadeStatus(uiDevIdx);
  }

  void EXTEND_DbgRead(binary_rsp& _return, const int32_t uiDevIdx, const int32_t uiLen) {
    helper->EXTEND_DbgRead(_return, uiDevIdx, uiLen);
  }

  int32_t EXTEND_DbgWrite(const int32_t uiDevIdx, const std::string& pucBuf, const int32_t uiLen) {
    return helper->EXTEND_DbgWrite(uiDevIdx, pucBuf, uiLen);
  }

  int32_t EXTEND_SetSfp(const int32_t uiDevIdx, const int32_t ulVal) {
    return helper->EXTEND_SetSfp(uiDevIdx, ulVal);
  }

  void MIRROR_GetStatusData(CMirrorData_rsp& _return, const int32_t uiDevIdx) {
    helper->MIRROR_GetStatusData(_return, uiDevIdx);
  }

  int32_t SWITCH_Pos(const int32_t uiDevIdx, const int32_t uiPort) {
    return helper->SWITCH_Pos(uiDevIdx, uiPort);
  }

  void MUX_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx) {
    helper->MUX_GetMfg(_return, uiDevIdx);
  }

  void MUX_GetStatusData(CMuxStatusData_rsp& _return, const int32_t uiDevIdx) {
    helper->MUX_GetStatusData(_return, uiDevIdx);
  }

  void MUX_GetCali(CMuxCaliData_rsp& _return, const int32_t uiDevIdx) {
    helper->MUX_GetCali(_return, uiDevIdx);
  }

  void OCM_GetMfg(CMfg_rsp& _return, const int32_t uiDevType) {
    helper->OCM_GetMfg(_return, uiDevType);
  }

  void OCM_GetStatusData(COcmStatusData_rsp& _return, const int32_t uiDevType) {
    helper->OCM_GetStatusData(_return, uiDevType);
  }

  void OCM_GetChPower(COcmChPower_rsp& _return, const int32_t uiDevType, const int32_t uiPortId) {
    helper->OCM_GetChPower(_return, uiDevType, uiPortId);
  }

  void OCM_GetOsaData(COcmOsa_rsp& _return, const int32_t uiDevType, const int32_t uiPortId) {
    helper->OCM_GetOsaData(_return, uiDevType, uiPortId);
  }

  void OCM_GetRealTimeOsaData(COcmOsa_rsp& _return, const int32_t uiDevType, const int32_t uiPortId) {
    helper->OCM_GetRealTimeOsaData(_return, uiDevType, uiPortId);
  }

  int32_t OCM_SetWaveplan(const int32_t uiDevType, const int32_t uiPortId, const int32_t uiChCnt, const std::vector<CWavePlanSlice_t> & pstWavePlan) {
    return helper->OCM_SetWaveplan(uiDevType, uiPortId, uiChCnt, pstWavePlan);
  }

  int32_t OCM_SetOcmWaveplan(const int32_t uiDevType, const int32_t uiPortId, const int32_t uiChCnt, const std::vector<STChannelGrid_t> & pstWavePlan) {
    return helper->OCM_SetOcmWaveplan(uiDevType, uiPortId, uiChCnt, pstWavePlan);
  }

  int32_t OCM_Reset(const int32_t uiDevType, const int8_t ucResetType) {
    return helper->OCM_Reset(uiDevType, ucResetType);
  }

  int32_t OCM_Upgrade(const int32_t uiDevType, const std::string& c_pcFilePath) {
    return helper->OCM_Upgrade(uiDevType, c_pcFilePath);
  }

  int32_t OCM_Commit(const int32_t uiDevType) {
    return helper->OCM_Commit(uiDevType);
  }

  int32_t OCM_GetUpgradeStatus(const int32_t uiDevType) {
    return helper->OCM_GetUpgradeStatus(uiDevType);
  }

  int32_t OCM_SetVoa(const int32_t uiDevType, const int16_t sAttn) {
    return helper->OCM_SetVoa(uiDevType, sAttn);
  }

  void OCM_GetVoa(i16_rsp& _return, const int32_t uiDevType) {
    helper->OCM_GetVoa(_return, uiDevType);
  }

  void OCM_GetVoaPd(i16_list_rsp& _return, const int32_t uiDevType) {
    helper->OCM_GetVoaPd(_return, uiDevType);
  }

  void OCS_GetMfg(CMfg_rsp& _return, const int32_t uiDevType)
  {
    helper->OCS_GetMfg(_return, uiDevType);
  }

  void OCS_GetStatusData(COcsStatusData_rsp& _return, const int32_t uiDevType)
  {
    helper->OCS_GetStatusData(_return, uiDevType);
  }

  int32_t OCS_SetConnection(const int32_t uiDevType, const COcsConnection_t& pstConnection)
  {
    return helper->OCS_SetConnection(uiDevType, pstConnection);
  }

  int32_t OCS_SetConnections(const int32_t uiDevType, const COcsConnections_t& pstConnections)
  {
    return helper->OCS_SetConnections(uiDevType, pstConnections);
  }

  int32_t OCS_SetLedState(const int32_t uiDevType, const int32_t index, const int32_t uiState)
  {
    return helper->OCS_SetLedState(uiDevType, index, uiState);
  }

  int32_t OCS_SetLedMode(const int32_t uiDevType, const int32_t uiMode)
  {
    return helper->OCS_SetLedMode(uiDevType, uiMode);
  }

  int32_t OCS_Reset(const int32_t uiDevType, const int8_t ucResetType)
  {
    return helper->OCS_Reset(uiDevType, ucResetType);
  }

  int32_t OCS_Upgrade(const int32_t uiDevType, const std::string& pcPath)
  {
    return helper->OCS_Upgrade(uiDevType, pcPath);
  }

  int32_t OCS_GetUpgradeStatus(const int32_t uiDevType)
  {
    return helper->OCS_GetUpgradeStatus(uiDevType);
  }

  void OPS_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx) {
    helper->OPS_GetMfg(_return, uiDevIdx);
  }

  void OPS_GetCommStatusData(COpsCommStatusData_rsp& _return, const int32_t uiDevIdx) {
    helper->OPS_GetCommStatusData(_return, uiDevIdx);
  }

  void OPS_GetCfgData(COpsCfgData_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId) {
     helper->OPS_GetCfgData(_return, uiDevIdx, uiPortId);
  }

  void OPS_GetStatusData(COpsStatusData_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId) {
    helper->OPS_GetStatusData(_return, uiDevIdx, uiPortId);
  }

  void OPS_GetHistoryData(COpsHistoryData_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId) {
    helper->OPS_GetHistoryData(_return, uiDevIdx, uiPortId);
  }

  void OPS_GetLedStatus(COpsLed_rsp& _return, const int32_t uiDevIdx) {
    helper->OPS_GetLedStatus(_return, uiDevIdx);
  }

  int32_t OPS_ClearAlarmDuration(const int32_t uiDevIdx) {
    return helper->OPS_ClearAlarmDuration(uiDevIdx);
  }

  int32_t OPS_SetThrPwrDiff(const int32_t uiDevIdx, const int16_t sThr, const int16_t sHys, const int32_t uiPortId) {
    return helper->OPS_SetThrPwrDiff(uiDevIdx, sThr, sHys, uiPortId);
  }

  int32_t OPS_SetThrLine(const int32_t uiDevIdx, const int32_t uiPortIdx, const int16_t sThr, const int16_t sHys, const int32_t uiPortId) {
    return helper->OPS_SetThrLine(uiDevIdx, uiPortIdx, sThr, sHys, uiPortId);
  }

  int32_t OPS_SetPortPowerThr(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sThr, const int32_t uiPortId) {
    return helper->OPS_SetPortPowerThr(uiDevIdx, uiPortIdx, uiType, sThr, uiPortId);
  }

  int32_t OPS_SetPortPowerHys(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sHys, const int32_t uiPortId) {
    return helper->OPS_SetPortPowerHys(uiDevIdx, uiPortIdx, uiType, sHys, uiPortId);
  }

  int32_t OPS_SetWtr(const int32_t uiDevIdx, const int32_t uiWtr, const int32_t uiPortId) {
    return helper->OPS_SetWtr(uiDevIdx, uiWtr, uiPortId);
  }

  int32_t OPS_SetHoldOffTime(const int32_t uiDevIdx, const int32_t uiHoldOffTime, const int32_t uiPortId) {
    return helper->OPS_SetHoldOffTime(uiDevIdx, uiHoldOffTime, uiPortId);
  }

  int32_t OPS_SetRevertive(const int32_t uiDevIdx, const bool bRevertive, const int32_t uiPortId) {
    return helper->OPS_SetRevertive(uiDevIdx, bRevertive, uiPortId);
  }

  int32_t OPS_SetMode(const int32_t uiDevIdx, const int32_t uiMode, const int32_t uiPortId) {
    return helper->OPS_SetMode(uiDevIdx, uiMode, uiPortId);
  }

  int32_t OPS_SetRelativeThr(const int32_t uiDevIdx, const int16_t sThr, const int32_t uiPortId) {
    return helper->OPS_SetRelativeThr(uiDevIdx, sThr, uiPortId);
  }

  int32_t OPS_SetRelativeOffset(const int32_t uiDevIdx, const int16_t sOffset, const int32_t uiPortId) {
    return helper->OPS_SetRelativeOffset(uiDevIdx, sOffset, uiPortId);
  }

  int32_t OPS_SetSwitchThr(const int32_t uiDevIdx, const int32_t uiPos, const int32_t iThr, const int32_t uiPortId) {
    return helper->OPS_SetSwitchThr(uiDevIdx, uiPos, iThr, uiPortId);
  }

  int32_t OPS_SetSwitchHys(const int32_t uiDevIdx, const int32_t uiPos, const int32_t iHys, const int32_t uiPortId) {
    return helper->OPS_SetSwitchHys(uiDevIdx, uiPos, iHys, uiPortId);
  }

  int32_t OPS_Reset(const int32_t uiDevIdx, const int8_t ucResetType) {
    return helper->OPS_Reset(uiDevIdx, ucResetType);
  }

  int32_t OPS_Upgrade(const int32_t uiDevIdx, const std::string& c_pcFilePath) {
    return helper->OPS_Upgrade(uiDevIdx, c_pcFilePath);
  }

  int32_t OPS_GetUpgadeStatus(const int32_t uiDevIdx) {
    return helper->OPS_GetUpgadeStatus(uiDevIdx);
  }

  int32_t OPS_SetLedDebugMode(const int32_t uiDevIdx, const int32_t uiMode) {
    return helper->OPS_SetLedDebugMode(uiDevIdx, uiMode);
  }

  int32_t OPS_SetLedStatus(const int32_t uiDevIdx, const int32_t uiLedIdx, const int32_t uiStatus) {
    return helper->OPS_SetLedStatus(uiDevIdx, uiLedIdx, uiStatus);
  }

  int32_t OPS_SetConnectionPdThr(const int32_t uiDevIdx, const int32_t uiPdIdx, const int32_t uiType, const int16_t sThr, const int32_t uiPortId) {
    return helper->OPS_SetConnectionPdThr(uiDevIdx, uiPdIdx, uiType, sThr, uiPortId);
  }

  int32_t OPS_SetConnectionPdHys(const int32_t uiDevIdx, const int32_t uiPdIdx, const int32_t uiType, const int16_t sHys, const int32_t uiPortId) {
    return helper->OPS_SetConnectionPdHys(uiDevIdx, uiPdIdx, uiType, sHys, uiPortId);
  }

  int32_t OPS_SetAlmMask(const int32_t uiDevType, const int32_t iMaskIdx, const int32_t iMaskVal, const int32_t uiPortId) {
    return helper->OPS_SetAlmMask(uiDevType, iMaskIdx, iMaskVal, uiPortId);
  }

  void OPS_GetEventLog(COpsEventLogAllData_rsp& _return, const int32_t uiDevType, const int32_t uiPortId) {
    helper->OPS_GetEventLog(_return, uiDevType, uiPortId);
  }

  int32_t OPS_SetRemoteStatus(const int32_t uiDevIdx, const COpsReqStatus_t& pstStatus, const int32_t uiPortId) {
    return helper->OPS_SetRemoteStatus(uiDevIdx, pstStatus, uiPortId);
  }

  void OPS_GetRequestStatus(COpsBidirectionStatus_rsp& _return, const int32_t uiDevIdx, const int32_t uiPortId) {
    helper->OPS_GetRequestStatus(_return, uiDevIdx, uiPortId);
  }

  int32_t OPS_SetSwitchingType(const int32_t uiDevIdx, const int8_t ucType, const int32_t uiPortId) {
    return helper->OPS_SetSwitchingType(uiDevIdx, ucType, uiPortId);
  }

  void OPS_GetOpsDevIdByKey(i32_list_rsp& _return, const std::string& pcName) {
    helper->OPS_GetOpsDevIdByKey(_return, pcName);
  }

  void OSC_GetStatusData(COscStatusData_rsp& _return, const int32_t uiDevType) {
    helper->OSC_GetStatusData(_return, uiDevType);
  }

  void OSC_GetCfgData(COscCfgData_rsp& _return, const int32_t uiDevType) {
    helper->OSC_GetCfgData(_return, uiDevType);
  }

  int32_t OSC_SetEnable(const int32_t uiDevType, const bool bEnable) {
    return helper->OSC_SetEnable(uiDevType, bEnable);
  }

  int32_t OSC_SetVoa(const int32_t uiDevType, const int32_t uiTxRx, const int16_t sAttn) {
    return helper->OSC_SetVoa(uiDevType, uiTxRx, sAttn);
  }

  void OSC_GetVoa(i16_rsp& _return, const int32_t uiDevType, const int32_t uiTxRx) {
    helper->OSC_GetVoa(_return, uiDevType, uiTxRx);
  }

  int32_t OSC_SetSwitchPos(const int32_t uiDevType, const COscSwitchPosSet_t& rstSwitchPos) {
    return helper->OSC_SetSwitchPos(uiDevType, rstSwitchPos);
  }

  void OSC_GetSwitchPos(COscSwitchPos_rsp& _return, const int32_t uiDevType) {
    helper->OSC_GetSwitchPos(_return, uiDevType);
  }

  void OTDR_GetMfg(CMfg_rsp& _return, const int32_t ulDevIdx) {
    helper->OTDR_GetMfg(_return, ulDevIdx);
  }

  void OTDR_GetStatusData(COtdrStatusData_rsp& _return, const int32_t ulDevIdx) {
    helper->OTDR_GetStatusData(_return, ulDevIdx);
  }

  void OTDR_GetCfgData(COtdrCfgData_rsp& _return, const int32_t ulDevIdx) {
    helper->OTDR_GetCfgData(_return, ulDevIdx);
  }

  int32_t OTDR_StartScan(const int32_t ulDevIdx) {
    return helper->OTDR_StartScan(ulDevIdx);
  }

  int32_t OTDR_SetPara(const int32_t ulDevIdx, const int32_t ulDistRang, const int32_t ulPulseWidth, const double dSamplingResolution) {
    return helper->OTDR_SetPara(ulDevIdx, ulDistRang, ulPulseWidth, dSamplingResolution);
  }

  int32_t OTDR_SetMeasuringTime(const int32_t ulDevIdx, const int32_t ulMeasuringTime) {
    return helper->OTDR_SetMeasuringTime(ulDevIdx, ulMeasuringTime);
  }

  int32_t OTDR_SetUserIOR(const int32_t ulDevIdx, const double dUserIOR) {
    return helper->OTDR_SetUserIOR(ulDevIdx, dUserIOR);
  }

  int32_t OTDR_SetThr(const int32_t ulDevIdx, const double dRefThr, const double dSpliceLosThr, const double dFiberEndThr) {
    return helper->OTDR_SetThr(ulDevIdx, dRefThr, dSpliceLosThr, dFiberEndThr);
  }

  int32_t OTDR_Reset(const int32_t ulDevIdx, const int8_t ucResetType) {
    return helper->OTDR_Reset(ulDevIdx, ucResetType);
  }

  int32_t OTDR_Upgrade(const int32_t ulDevIdx, const std::string& c_pcFilePath) {
    return helper->OTDR_Upgrade(ulDevIdx, c_pcFilePath);
  }

  int32_t OTDR_GetUpgadeStatus(const int32_t ulDevIdx) {
    return helper->OTDR_GetUpgadeStatus(ulDevIdx);
  }

  void OTDR_DbgRead(binary_rsp& _return, const int32_t ulDevIdx, const int32_t uiLen) {
    helper->OTDR_DbgRead(_return, ulDevIdx, uiLen);
  }

  int32_t OTDR_DbgWrite(const int32_t ulDevIdx, const std::string& pucBuf, const int32_t uiLen) {
    return helper->OTDR_DbgWrite(ulDevIdx, pucBuf, uiLen);
  }

  int32_t OTDR_SetScanMode(const int32_t uiDevType, const int32_t ulScanMode) {
    return helper->OTDR_SetScanMode(uiDevType, ulScanMode);
  }

  int32_t OTDR_SetStartOffset(const int32_t uiDevType, const COtdrStartOffset_t& pstStartOffset) {
    return helper->OTDR_SetStartOffset(uiDevType, pstStartOffset);
  }

  void OTDR_GetStartOffset(COtdrStartOffset_rsp& _return, const int32_t uiDevType) {
    helper->OTDR_GetStartOffset(_return, uiDevType);
  }

  int32_t OTDR_StartScanPort(const int32_t ulDevIdx, const int32_t ulPortId) {
    return helper->OTDR_StartScanPort(ulDevIdx, ulPortId);
  }

  void SLOT_GetDevIdx(i32_list_rsp& _return, const int32_t uiDevType) {
    helper->SLOT_GetDevIdx(_return, uiDevType);
  }

  int32_t SLOT_SetOnline(const int32_t uiSlotIdx, const bool bOnline) {
    return helper->SLOT_SetOnline(uiSlotIdx, bOnline);
  }

  void SLOT_GetSlotNum(i32_rsp& _return) {
    helper->SLOT_GetSlotNum(_return);
  }

  int32_t SLOT_SetMfg(const int32_t uiSlotIdx, const std::string& c_pcFilePath) {
    return helper->SLOT_SetMfg(uiSlotIdx, c_pcFilePath);
  }

  void SLOT_GetMfg(CMfg_rsp& _return, const int32_t uiSlotIdx) {
    helper->SLOT_GetMfg(_return, uiSlotIdx);
  }

  void SLOT_GetStatusData(CSlotStatusData_rsp& _return, const int32_t uiSlotIdx) {
    helper->SLOT_GetStatusData(_return, uiSlotIdx);
  }

  int32_t SLOT_ClearPlugFlag(const int32_t uiSlotIdx) {
    return helper->SLOT_ClearPlugFlag(uiSlotIdx);
  }

  void SLOT_GetInfo(CSlotInfo_rsp& _return, const int32_t uiSlotIdx) {
    helper->SLOT_GetInfo(_return, uiSlotIdx);
  }

  void SLOT_GetCali(CCali_rsp& _return, const int32_t uiSlotIdx) {
    helper->SLOT_GetCali(_return, uiSlotIdx);
  }

  int32_t SLOT_SetCali(const int32_t uiSlotIdx, const std::string& c_pcFilePath) {
    return helper->SLOT_SetCali(uiSlotIdx, c_pcFilePath);
  }

  int32_t SLOT_Reset(const int32_t uiSlotIdx, const int8_t ucResetType) {
    return helper->SLOT_Reset(uiSlotIdx, ucResetType);
  }

  int32_t SLOT_SetLed(const int32_t uiSlotIdx, const int32_t uiLedIdx, const int32_t uiState) {
    return helper->SLOT_SetLed(uiSlotIdx, uiLedIdx, uiState);
  }

  void SLOT_ReadEeprom(binary_rsp& _return, const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen) {
    helper->SLOT_ReadEeprom(_return, uiIdx, ulAddr, ulLen);
  }

  int32_t SLOT_WriteEeprom(const int32_t uiIdx, const int64_t ulAddr, const int64_t ulLen, const std::string& pucVal) {
    return helper->SLOT_WriteEeprom(uiIdx, ulAddr, ulLen, pucVal);
  }

  void TDCM_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx) {
    helper->TDCM_GetMfg(_return, uiDevIdx);
  }

  void TDCM_GetStatusData(CTdcmStatusData_rsp& _return, const int32_t uiDevIdx) {
    helper->TDCM_GetStatusData(_return, uiDevIdx);
  }

  void TDCM_GetCfgData(CTdcmCfgData_rsp& _return, const int32_t uiDevIdx) {
    helper->TDCM_GetCfgData(_return, uiDevIdx);
  }

  int32_t TDCM_SetFrequency(const int32_t uiDevIdx, const double fFrequency) {
    return helper->TDCM_SetFrequency(uiDevIdx, fFrequency);
  }

  int32_t TDCM_SetDispersion(const int32_t uiDevIdx, const double fDispersion) {
    return helper->TDCM_SetDispersion(uiDevIdx, fDispersion);
  }

  int32_t TDCM_Reset(const int32_t uiDevIdx, const int8_t ucResetType) {
    return helper->TDCM_Reset(uiDevIdx, ucResetType);
  }

  void WSS_GetMfg(CMfg_rsp& _return, const int32_t uiDevIdx) {
    helper->WSS_GetMfg(_return, uiDevIdx);
  }

  void WSS_GetCfg(CWssAllCfg_rsp& _return, const int32_t uiDevIdx) {
    helper->WSS_GetCfg(_return, uiDevIdx);
  }

  void WSS_GetOscCfg(CWssAllCfg_rsp& _return, const int32_t uiDevIdx) {
    helper->WSS_GetOscCfg(_return, uiDevIdx);
  }

  void WSS_GetStatusData(CWssStatusData_rsp& _return, const int32_t uiDevIdx) {
    helper->WSS_GetStatusData(_return, uiDevIdx);
  }

  int32_t WSS_SetAllChCfg(const int32_t uiDevIdx, const int32_t uiSubIdx, const int32_t uiChCnt, const std::vector<CWssCfg_t> & pstWssCfg) {
    return helper->WSS_SetAllChCfg(uiDevIdx, uiSubIdx, uiChCnt, pstWssCfg);
  }

  int32_t WSS_SetOscChCfg(const int32_t uiDevIdx, const int32_t uiSubIdx, const int32_t uiChCnt, const std::vector<CWssCfg_t> & pstWssCfg) {
    return helper->WSS_SetOscChCfg(uiDevIdx, uiSubIdx, uiChCnt, pstWssCfg);
  }

  int32_t WSS_SetWaveplan(const int32_t uiDevIdx, const int32_t uiSubIdx, const int32_t uiChCnt, const std::vector<CWavePlan_t> & pstWavePlan) {
    return helper->WSS_SetWaveplan(uiDevIdx, uiSubIdx, uiChCnt, pstWavePlan);
  }

  int32_t WSS_SetPortPowerThr(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sThr) {
    return helper->WSS_SetPortPowerThr(uiDevIdx, uiPortIdx, uiType, sThr);
  }

  int32_t WSS_SetPortPowerHys(const int32_t uiDevIdx, const int32_t uiPortIdx, const int32_t uiType, const int16_t sHys) {
    return helper->WSS_SetPortPowerHys(uiDevIdx, uiPortIdx, uiType, sHys);
  }

  int32_t WSS_GetPortPowerHistory(const int32_t uiDevIdx) {
    return helper->WSS_GetPortPowerHistory(uiDevIdx);
  }

  int32_t WSS_SetLedMode(const int32_t uiDevIdx, const int32_t uiMode) {
    return helper->WSS_SetLedMode(uiDevIdx, uiMode);
  }

  int32_t WSS_SetLedDebugMode(const int32_t uiDevIdx, const int32_t uiMode) {
    return helper->WSS_SetLedDebugMode(uiDevIdx, uiMode);
  }

  int32_t WSS_SetLedStatus(const int32_t uiDevIdx, const int32_t uiLedIdx, const int32_t uiStatus) {
    return helper->WSS_SetLedStatus(uiDevIdx, uiLedIdx, uiStatus);
  }

  int32_t WSS_Reset(const int32_t uiDevIdx, const int8_t ucResetType) {
    return helper->WSS_Reset(uiDevIdx, ucResetType);
  }

  int32_t WSS_Upgrade(const int32_t uiDevIdx, const std::string& c_pcFilePath) {
    return helper->WSS_Upgrade(uiDevIdx, c_pcFilePath);
  }

  int32_t WSS_GetUpgradeStatus(const int32_t uiDevIdx) {
    return helper->WSS_GetUpgradeStatus(uiDevIdx);
  }

  int32_t WSS_SetUserData(const int32_t uiDevIdx, const std::string& pucData, const int32_t nLen) {
    return helper->WSS_SetUserData(uiDevIdx, pucData, nLen);
  }

  void WSS_GetUserData(binary_rsp& _return, const int32_t uiDevIdx, const int32_t nLen) {
    helper->WSS_GetUserData(_return, uiDevIdx, nLen);
  }

  int32_t WSS_SetPmUserData(const int32_t uiDevIdx, const std::string& pucData, const int32_t nLen) {
    return helper->WSS_SetPmUserData(uiDevIdx, pucData, nLen);
  }

  void WSS_GetPmUserData(binary_rsp& _return, const int32_t uiDevIdx, const int32_t nLen) {
    helper->WSS_GetPmUserData(_return, uiDevIdx, nLen);
  }

private:
  ::std::shared_ptr<HalApiIf> helper = ::std::make_shared<ApiHelper>();

};

int main(int argc, char **argv) {
  ::std::shared_ptr<HalApiHandler> handler(new HalApiHandler());
  ::std::shared_ptr<TProcessor> processor(new HalApiProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(DEF_THRIFT_ADDR, DEF_THRIFT_PORT));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TThreadedServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

